# @req SCI-HELM-006
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdd-navigator.fullname" . }}-api
  labels:
    {{- include "sdd-navigator.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "sdd-navigator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api