# @req SCI-HELM-005
# @req SCI-NONEXISTENT-999
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdd-navigator.fullname" . }}-config
  labels:
    {{- include "sdd-navigator.labels" . | nindent 4 }}
data:
  logLevel: {{ .Values.api.config.logLevel | quote }}
  dbHost: {{ .Values.api.config.dbHost | quote }}