# @req SCI-HELM-005
# @req SCI-HELM-006
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-config
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  api.port: "{{ .Values.port }}"
  log.level: "{{ .Values.config.logLevel }}"
  database.host: "{{ .Values.config.dbHost }}"
  database.port: "{{ .Values.config.dbPort }}"
  database.name: "{{ .Values.config.dbName }}"
