# @req SCI-HELM-005
# @req SCI-HELM-006
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-secret
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  database.user: "{{ .Values.config.dbUser }}"
  database.password: "PLACEHOLDER_MUST_OVERRIDE"
